'use client';
import {emptyForm,emptyServiceForm,formFields,serviceFormFields,type FormContent} from '@/lib/form-content';
import type {ServiceItem} from '@/lib/plan-content';
import {inputClass,buttonClass} from './BusinessShell';
export default function PlanForms({value,services,onChange}:{value?:FormContent;services:ServiceItem[];onChange:(v:FormContent)=>void}){
 const f=value??emptyForm();
 return <details className="space-y-4 border p-4"><summary>名古屋市帳票の追加情報</summary><p>架空データのみ入力してください。空欄は未確認、該当しない項目は「該当なし」と入力します。追加情報も計画と一緒に保存・別人承認されます。署名は自動作成しません。</p>
 {formFields.map(([k,label])=><label className="block" key={k}>{label}<textarea className={inputClass} rows={2} maxLength={2000} value={f[k]} onChange={e=>onChange({...f,[k]:e.target.value})}/></label>)}
 {services.map(s=>{const row=f.services.find(x=>x.serviceId===s.id)??emptyServiceForm(s.id);const change=(k:string,v:string)=>onChange({...f,services:[...f.services.filter(x=>x.serviceId!==s.id&&services.some(a=>a.id===x.serviceId)),{...row,[k]:v}]});return <fieldset key={s.id} className="space-y-2 rounded border p-3"><legend>{s.serviceName||'名称未入力サービス'} の帳票項目</legend>{serviceFormFields.map(([k,label])=><label className="block" key={k}>{label}<textarea className={inputClass} rows={2} maxLength={2000} value={row[k]} onChange={e=>change(k,e.target.value)}/></label>)}{([['typeChange','サービス種類の変更'],['amountChange','サービス量の変更'],['weekChange','週間計画の変更']] as const).map(([k,label])=><label className="block" key={k}>{label}<select className={inputClass} value={row[k]} onChange={e=>change(k,e.target.value)}>{['','有','無','未確認','該当なし'].map(v=><option key={v} value={v}>{v||'未入力'}</option>)}</select></label>)}</fieldset>;})}
 <h3>週間予定</h3>{f.weekly.map((w,i)=><fieldset key={i} className="space-y-2 border p-3"><legend>予定 {i+1}</legend><label>曜日<select className={inputClass} value={w.day} onChange={e=>onChange({...f,weekly:f.weekly.map((x,j)=>j===i?{...x,day:Number(e.target.value)}:x)})}>{['月','火','水','木','金','土','日・祝'].map((d,j)=><option key={d} value={j}>{d}</option>)}</select></label>{(['start','end'] as const).map(k=><label key={k}>{k==='start'?'開始':'終了'}<input type="time" className={inputClass} value={w[k]} onChange={e=>onChange({...f,weekly:f.weekly.map((x,j)=>j===i?{...x,[k]:e.target.value}:x)})}/></label>)}<label>活動<textarea className={inputClass} maxLength={500} value={w.activity} onChange={e=>onChange({...f,weekly:f.weekly.map((x,j)=>j===i?{...x,activity:e.target.value}:x)})}/></label><button type="button" className={buttonClass} onClick={()=>onChange({...f,weekly:f.weekly.filter((_,j)=>j!==i)})}>この予定を外す</button></fieldset>)}<button type="button" className={buttonClass} onClick={()=>onChange({...f,weekly:[...f.weekly,{day:0,start:'09:00',end:'10:00',activity:''}]})}>週間予定を追加</button>
 <p>モニタリング欄は、この承認資料に含める報告内容です。既存モニタリング記録から自動転記せず、実施日と目標別の内容を照合して入力してください。</p></details>;
}
