import assert from 'node:assert/strict';
import fs from 'node:fs';
import ExcelJS from 'exceljs';
import {nagoyaWorkbook,NAGOYA_TEMPLATE} from '../lib/nagoya-export.ts';
const snapshot={planId:'70000000-0000-4000-8000-000000000001',revision:1,status:'approved',user:{id:'70000000-0000-4000-8000-000000000002',name:'架空帳票利用者'},facility:{id:'70000000-0000-4000-8000-000000000003',name:'架空相談支援事業所'},createdAt:'2026-09-29T00:00:00Z',approvedAt:'2026-09-29T01:00:00Z',approverId:'70000000-0000-4000-8000-000000000004',outputAt:'2026-09-29T02:00:00Z',templateVersion:'mirai-review-v1',content:{planPeriodStart:'2026-10-01',planPeriodEnd:'2027-03-31',createdDate:'2026-09-29',monitoringDate:'2026-12-01',userWish:'架空：地域活動に参加したい',familyWish:'架空：本人の選択を尊重する',overallPolicy:'架空：本人の希望を確認する',longTermGoal:'架空：希望する活動に参加する',shortTermGoal:'架空：見学して選ぶ',services:[{id:'1',serviceName:'架空サービス',content:'=HYPERLINK("https://example.invalid","literal")',frequency:'架空：月1回'}]}};
const workbook=await nagoyaWorkbook(snapshot);const bytes=await workbook.xlsx.writeBuffer();
const restored=new ExcelJS.Workbook();await restored.xlsx.load(bytes);
assert.equal(restored.getWorksheet('計画').getCell('I4').value,snapshot.user.name);
assert.equal(restored.getWorksheet('計画').getCell('I12').value,snapshot.content.overallPolicy);
assert.equal(restored.getWorksheet('計画').getCell('X18').type,ExcelJS.ValueType.String);
assert.match(restored.getWorksheet('計画').getCell('X18').value,/=HYPERLINK/);
assert.equal(restored.getWorksheet('出力情報・未入力項目').getCell('B2').value,NAGOYA_TEMPLATE);
assert.equal(restored.getWorksheet('出力情報・未入力項目').getCell('B5').value,'1');
assert.match(restored.getWorksheet('計画').headerFooter.oddHeader,/提出不可/);
await assert.rejects(nagoyaWorkbook({...snapshot,status:'draft'}));
await assert.rejects(nagoyaWorkbook({...snapshot,content:{...snapshot.content,services:Array(7).fill(snapshot.content.services[0])}}));
await assert.rejects(nagoyaWorkbook({...snapshot,content:{...snapshot.content,userWish:'a'.repeat(2001)}}));
fs.mkdirSync('test-results',{recursive:true});await workbook.xlsx.writeFile('test-results/nagoya-synthetic.xlsx');
fs.writeFileSync('test-results/forms.json',JSON.stringify({templateVersion:NAGOYA_TEMPLATE,syntheticOnly:true,literalStrings:true,metadata:true,unapprovedDenied:true,overflowDenied:true,missingFieldsExplicit:true,formalSubmissionReady:false},null,2));
console.log('PASS: Nagoya mapping, literal text, approval guard, overflow rejection and trace metadata');
